linux-dreambox: Remove PKG:{PN} which rename to existing package
ERROR: linux-dreambox-3.2-r14.20.90 do_package: package "kernel-base" is renamed to "kernel-base" using PKG:kernel-base, but package name already exists

https://git.openembedded.org/openembedded-core/commit/?id=f6cb63d3a871c4eef52d981131a56bf41aa1dcdf